In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the same raw file EDA used
df = pd.read_csv("../data/processed/laps_2023.csv")

print("Shape of the dataset:", df.shape)

Shape of the dataset: (11255, 33)


In [4]:
pd.set_option("display.max_columns", None)
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,0 days 01:02:36.652000,NaN,12,1.0,NaN,NaN,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,0 days 01:04:15.902000,NaN,12,1.0,NaN,NaN,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,0 days 01:05:53.876000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,0 days 01:07:31.882000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,0 days 01:09:09.858000,NaN,1,1.0,NaN,NaN,False,True,Bahrain,2023


In [7]:
# Drop useless columns (100% missing)
df.drop(columns = ["LapStartDate", "Deleted", "DeletedReason"], inplace = True)
df.head()


,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year
0,0 days 01:04:15.902000,VER,1,0 days 00:01:39.019000,1.0,1.0,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,0 days 01:02:36.652000,12,1.0,False,False,Bahrain,2023
1,0 days 01:05:53.876000,VER,1,0 days 00:01:37.974000,2.0,1.0,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,0 days 01:04:15.902000,12,1.0,False,True,Bahrain,2023
2,0 days 01:07:31.882000,VER,1,0 days 00:01:38.006000,3.0,1.0,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,0 days 01:05:53.876000,1,1.0,False,True,Bahrain,2023
3,0 days 01:09:09.858000,VER,1,0 days 00:01:37.976000,4.0,1.0,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,0 days 01:07:31.882000,1,1.0,False,True,Bahrain,2023
4,0 days 01:10:47.893000,VER,1,0 days 00:01:38.035000,5.0,1.0,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,0 days 01:09:09.858000,1,1.0,False,True,Bahrain,2023


In [9]:
df.shape

(11255, 30)

#### Features with 100% missing values were dropped cause it carries zero information

---------------------------------------------------------------

In [13]:
# Time related columns 
time_col = [feature for feature in df.columns if ("Time" in feature) or ("Date" in feature)]
print(time_col)

df[time_col].head(10)

['Time', 'LapTime', 'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time', 'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime', 'LapStartTime']


,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,0 days 01:04:15.902000,0 days 00:01:39.019000,NaN,NaN,NaN,0 days 00:00:42.414000,0 days 00:00:23.842000,NaN,0 days 01:03:52.119000,0 days 01:04:16.010000,0 days 01:02:36.652000
1,0 days 01:05:53.876000,0 days 00:01:37.974000,NaN,NaN,0 days 00:00:31.342000,0 days 00:00:42.504000,0 days 00:00:24.128000,0 days 01:04:47.303000,0 days 01:05:29.807000,0 days 01:05:53.935000,0 days 01:04:15.902000
2,0 days 01:07:31.882000,0 days 00:01:38.006000,NaN,NaN,0 days 00:00:31.388000,0 days 00:00:42.469000,0 days 00:00:24.149000,0 days 01:06:25.323000,0 days 01:07:07.792000,0 days 01:07:31.941000,0 days 01:05:53.876000
3,0 days 01:09:09.858000,0 days 00:01:37.976000,NaN,NaN,0 days 00:00:31.271000,0 days 00:00:42.642000,0 days 00:00:24.063000,0 days 01:08:03.212000,0 days 01:08:45.854000,0 days 01:09:09.917000,0 days 01:07:31.882000
4,0 days 01:10:47.893000,0 days 00:01:38.035000,NaN,NaN,0 days 00:00:31.244000,0 days 00:00:42.724000,0 days 00:00:24.067000,0 days 01:09:41.161000,0 days 01:10:23.885000,0 days 01:10:47.952000,0 days 01:09:09.858000
5,0 days 01:12:25.879000,0 days 00:01:37.986000,NaN,NaN,0 days 00:00:31.341000,0 days 00:00:42.632000,0 days 00:00:24.013000,0 days 01:11:19.293000,0 days 01:12:01.925000,0 days 01:12:25.938000,0 days 01:10:47.893000
6,0 days 01:14:03.900000,0 days 00:01:38.021000,NaN,NaN,0 days 00:00:31.290000,0 days 00:00:42.763000,0 days 00:00:23.968000,0 days 01:12:57.228000,0 days 01:13:39.991000,0 days 01:14:03.959000,0 days 01:12:25.879000
7,0 days 01:15:42.054000,0 days 00:01:38.154000,NaN,NaN,0 days 00:00:31.291000,0 days 00:00:42.833000,0 days 00:00:24.030000,0 days 01:14:35.250000,0 days 01:15:18.083000,0 days 01:15:42.113000,0 days 01:14:03.900000
8,0 days 01:17:20.332000,0 days 00:01:38.278000,NaN,NaN,0 days 00:00:31.336000,0 days 00:00:42.823000,0 days 00:00:24.119000,0 days 01:16:13.449000,0 days 01:16:56.272000,0 days 01:17:20.391000,0 days 01:15:42.054000
9,0 days 01:18:58.701000,0 days 00:01:38.369000,NaN,NaN,0 days 00:00:31.361000,0 days 00:00:42.884000,0 days 00:00:24.124000,0 days 01:17:51.752000,0 days 01:18:34.636000,0 days 01:18:58.760000,0 days 01:17:20.332000


In [15]:
# Convert timedelta ----> seconds


# Strip column name incase of hidden space
df.columns = df.columns.str.strip()

for col in time_col:
    df[col]= pd.to_timedelta(df[col], errors = "coerce").dt.total_seconds()

df[time_col].head()

,Time,LapTime,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,LapStartTime
0,3855.902,99.019,NaN,NaN,NaN,42.414,23.842,NaN,3832.119,3856.010,3756.652
1,3953.876,97.974,NaN,NaN,31.342,42.504,24.128,3887.303,3929.807,3953.935,3855.902
2,4051.882,98.006,NaN,NaN,31.388,42.469,24.149,3985.323,4027.792,4051.941,3953.876
3,4149.858,97.976,NaN,NaN,31.271,42.642,24.063,4083.212,4125.854,4149.917,4051.882
4,4247.893,98.035,NaN,NaN,31.244,42.724,24.067,4181.161,4223.885,4247.952,4149.858


In [16]:
print(df[time_col].dtypes)

Time                  float64
LapTime               float64
PitOutTime            float64
PitInTime             float64
Sector1Time           float64
Sector2Time           float64
Sector3Time           float64
Sector1SessionTime    float64
Sector2SessionTime    float64
Sector3SessionTime    float64
LapStartTime          float64
dtype: object


--------

In [20]:
# Fix categorical vs numerical cols
categorical_numeric = ["DriverNumber", "Year", "Position", "TrackStatus"]

print(df[categorical_numeric].dtypes, "\n\n")


for col in categorical_numeric:
    df[col] = df[col].astype("category")

print(df[categorical_numeric].dtypes, "\n")

DriverNumber      int64
Year              int64
Position        float64
TrackStatus       int64
dtype: object 


DriverNumber    category
Year            category
Position        category
TrackStatus     category
dtype: object 



In [22]:
# Fix boolean cols
bool_cols = [feature for feature in df.columns if df[feature].dtype == "bool"]

print(bool_cols, "\n")

# IsPersonalBest is a bool value but stored as an object 
bool_cols.append("IsPersonalBest")
print(bool_cols, "\n\n")


for col in bool_cols:
    df[col] = df[col].map({
        True: True,
        False: False,
        "True": True, 
        "False": False,
        None: pd.NA,
        "nan": pd.NA
    })
    df[col] = df[col].astype("bool")




print(df[bool_cols].head())
print(df[bool_cols].dtypes)

['FreshTyre', 'FastF1Generated', 'IsAccurate'] 

['FreshTyre', 'FastF1Generated', 'IsAccurate', 'IsPersonalBest'] 


   FreshTyre  FastF1Generated  IsAccurate  IsPersonalBest
0      False            False       False           False
1      False            False        True            True
2      False            False        True           False
3      False            False        True           False
4      False            False        True           False
FreshTyre          bool
FastF1Generated    bool
IsAccurate         bool
IsPersonalBest     bool
dtype: object


---------

In [27]:
# Create Target Variable 

# PitInTime contains the time a driver entered the pit lane
# If PitInTime has a value = driver pitted that lap = 1
# If PitInTime is NaN = driver stayed out = 0

df["Pitted"] = df["PitInTime"].notna().astype(int)

print("Pit stop distribution:")
print(df["Pitted"].value_counts())
print(f"\nPit Stop rate: {df['Pitted'].mean():.2f}")

Pit stop distribution:
Pitted
0    10878
1      377
Name: count, dtype: int64

Pit Stop rate: 0.03


In [29]:
# Drop PitInTime and PitOutTime
# We already extracted the signal we need (Pitted column)
# Model must never see these 

df.drop(columns = ["PitInTime", "PitOutTime"], inplace = True)
# inplace = True modifys the existing dataframe directly instead of creating a new one

print("Columns remaining:", df.shape[1])

Columns remaining: 29


In [31]:
df.shape

(11255, 29)

In [33]:
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year,Pitted
0,3855.902,VER,1,99.019,1.0,1.0,NaN,42.414,23.842,NaN,3832.119,3856.010,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,3756.652,12,1.0,False,False,Bahrain,2023,0
1,3953.876,VER,1,97.974,2.0,1.0,31.342,42.504,24.128,3887.303,3929.807,3953.935,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,3855.902,12,1.0,False,True,Bahrain,2023,0
2,4051.882,VER,1,98.006,3.0,1.0,31.388,42.469,24.149,3985.323,4027.792,4051.941,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,3953.876,1,1.0,False,True,Bahrain,2023,0
3,4149.858,VER,1,97.976,4.0,1.0,31.271,42.642,24.063,4083.212,4125.854,4149.917,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,4051.882,1,1.0,False,True,Bahrain,2023,0
4,4247.893,VER,1,98.035,5.0,1.0,31.244,42.724,24.067,4181.161,4223.885,4247.952,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,4149.858,1,1.0,False,True,Bahrain,2023,0


---

#### Encode Tyre Compounds
#### We encode by durability - how long each compound lasts

```
SOFT = 0 ---> degrades fastest 
MEDIUM = 1 ---> middle 
HARD = 2 ---> most durable 
INTERMEDIATE = 3 --> wet conditions
WET = 4 --> full wet

```

In [36]:
# Map each compound to a number 

compound_map = {
    "SOFT": 0,
    "MEDIUM": 1, 
    "HARD": 2, 
    "INTERMEDIATE": 3, 
    "WET" : 4
}

df["CompoundEncoded"] = df["Compound"].map(compound_map)

# Check for any compounds we missed 
print("Unmapped compounds:", df[df["CompoundEncoded"].isna()]["Compound"].unique())


# Confirm distribution 
print("\nCompound distribution")
print(df.groupby("Compound")["CompoundEncoded"].first())

Unmapped compounds: []

Compound distribution
Compound
HARD            2
INTERMEDIATE    3
MEDIUM          1
SOFT            0
WET             4
Name: CompoundEncoded, dtype: int64


In [38]:
df.head()

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,IsPersonalBest,Compound,TyreLife,FreshTyre,Team,LapStartTime,TrackStatus,Position,FastF1Generated,IsAccurate,RaceName,Year,Pitted,CompoundEncoded
0,3855.902,VER,1,99.019,1.0,1.0,NaN,42.414,23.842,NaN,3832.119,3856.010,232.0,231.0,278.0,252.0,False,SOFT,4.0,False,Red Bull Racing,3756.652,12,1.0,False,False,Bahrain,2023,0,0
1,3953.876,VER,1,97.974,2.0,1.0,31.342,42.504,24.128,3887.303,3929.807,3953.935,227.0,238.0,278.0,288.0,True,SOFT,5.0,False,Red Bull Racing,3855.902,12,1.0,False,True,Bahrain,2023,0,0
2,4051.882,VER,1,98.006,3.0,1.0,31.388,42.469,24.149,3985.323,4027.792,4051.941,227.0,238.0,278.0,287.0,False,SOFT,6.0,False,Red Bull Racing,3953.876,1,1.0,False,True,Bahrain,2023,0,0
3,4149.858,VER,1,97.976,4.0,1.0,31.271,42.642,24.063,4083.212,4125.854,4149.917,228.0,238.0,278.0,289.0,False,SOFT,7.0,False,Red Bull Racing,4051.882,1,1.0,False,True,Bahrain,2023,0,0
4,4247.893,VER,1,98.035,5.0,1.0,31.244,42.724,24.067,4181.161,4223.885,4247.952,228.0,239.0,278.0,290.0,False,SOFT,8.0,False,Red Bull Racing,4149.858,1,1.0,False,True,Bahrain,2023,0,0


-----

In [40]:
# Tyre Degradation Features 
# Features that tell the model what's happening to the tyres RIGHT NOW


# Sort by race -> driver -> stint -> lap number 
# This ensures laps are in chronological order 
# per driver per stint

df = df.sort_values(
    ["RaceName", "Driver", "Stint", "LapNumber"]
).reset_index(drop = True)

print("Data sorted correctly")
df[["RaceName", "Driver", "Stint", "LapNumber", "LapTime"]].head()



Data sorted correctly


,RaceName,Driver,Stint,LapNumber,LapTime
0,Abu Dhabi,ALB,1.0,1.0,100.625
1,Abu Dhabi,ALB,1.0,2.0,93.560
2,Abu Dhabi,ALB,1.0,3.0,91.768
3,Abu Dhabi,ALB,1.0,4.0,91.591
4,Abu Dhabi,ALB,1.0,5.0,91.422


In [42]:
# Lap 1: 100.6s <- slow, just started, cold tyres
# Lap 2: 93.6s <- much faster, tyres warming up
# Lap 3: 91.7s <- getting faster 
# Lap 4: 91.5s <- peak performance
# Lap 5: 91.4s <- still near peak 


# Tyres start cold, warm up, peak, then slowly degrade.

#### Tyre Degradation features 

```
Why we are builiding these features:
the raw data only tells us:

TyreLife = 21
LapTime = 92.3s

But the model needs to understand what's happening over time.
- Is the tyre getting slower?
- How much slower vs when it was new?
- Is the degradation speeding up?

A single lap time number doesn't tell us that. so we need to compare it to previous laps. 
```
##### 1. FEATURE 1: LapTimeDelta

In [45]:
# LapTimeDelta 
# How much slower is this lap compared to the previous lap?
# Captures : is the tyre degrading RIGHT NOW?

#.diff() calculates the difference between current row and the previous row 
# We group by Race + Driver + Stint so we don't calculate delta across different stints or different drivers


# Positive = getting slower = tyre degrading 
# Negative = getting faster = tyre warming up

df["LapTimeDelta"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTime"].diff()

df[["RaceName", "Driver", "Stint", 
    "LapNumber", "LapTime", "LapTimeDelta"]].head(10)

,RaceName,Driver,Stint,LapNumber,LapTime,LapTimeDelta
0,Abu Dhabi,ALB,1.0,1.0,100.625,NaN
1,Abu Dhabi,ALB,1.0,2.0,93.560,-7.065
2,Abu Dhabi,ALB,1.0,3.0,91.768,-1.792
3,Abu Dhabi,ALB,1.0,4.0,91.591,-0.177
4,Abu Dhabi,ALB,1.0,5.0,91.422,-0.169
5,Abu Dhabi,ALB,1.0,6.0,91.491,0.069
6,Abu Dhabi,ALB,1.0,7.0,91.438,-0.053
7,Abu Dhabi,ALB,1.0,8.0,91.580,0.142
8,Abu Dhabi,ALB,1.0,9.0,91.644,0.064
9,Abu Dhabi,ALB,1.0,10.0,91.978,0.334


```
Lap 1: NaN ---> no previous lap to compare, expected
Lap 2: -7.065 --> 7 seconds faster than Lap 1 (tyre warming up)
Lap 3: -1.792 --> still getting faster
Lap 4: -0.177 --> nearly stabilized
Lap 5 - 10 : small fluctuations around 0


--- lap 1 is always slow(cold tyres, traffic from pit exit), then the car rapidly speeds up as tyres warm up, then it stabilizes.

```

##### 2. FEATURE 2: LapTimeRolling

In [48]:
# Average lap time over the LAST 3 laps
# Captures: what is the underlying pace right now?
# Why 3 laps: One bad lap could be traffic or a yellow flag, averaging 3 laps smooths out that noise

df["LapTimeRolling3"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTime"].transform(
    lambda x: x.rolling(window = 3, min_periods = 1).mean()

)

df[["Driver", "Stint", "LapNumber",
    "LapTime", "LapTimeRolling3"]].head(10)

,Driver,Stint,LapNumber,LapTime,LapTimeRolling3
0,ALB,1.0,1.0,100.625,100.625000
1,ALB,1.0,2.0,93.560,97.092500
2,ALB,1.0,3.0,91.768,95.317667
3,ALB,1.0,4.0,91.591,92.306333
4,ALB,1.0,5.0,91.422,91.593667
5,ALB,1.0,6.0,91.491,91.501333
6,ALB,1.0,7.0,91.438,91.450333
7,ALB,1.0,8.0,91.580,91.503000
8,ALB,1.0,9.0,91.644,91.554000
9,ALB,1.0,10.0,91.978,91.734000


```

Lap 1: 100.625 --> just lap 1 alone (only 1 data point so far)
Lap 2: 97.09 --> average of laps 1 - 2
Lap 3: 95.32 --> average of laps 1 - 3
Lap 4: 92.31 --> average of laps 2- 4 (rolling window of 3)

--- by lap 5 onwards it's hovering around 91.5, which matches the stabilized pace

```

##### 3. FEATURE 3: DegradationFromStintStart

In [55]:
# How much slower are we NOW vs lap 1 of this stint?
# Captures: TOTAL Performance loss on this tyre set 
# eg:  +3.2s means 3.2 seconds slower than when tyre was fresh

df["DegradationFromStintStart"] = df.groupby (
    ["RaceName", "Driver", "Stint"]
)["LapTime"].transform(
    lambda x: x - x.iloc[0]
)

df[["Driver", "Stint", "LapTime",
    "LapTime", "DegradationFromStintStart"]].head(10)

,Driver,Stint,LapTime,LapTime,DegradationFromStintStart
0,ALB,1.0,100.625,100.625,0.000
1,ALB,1.0,93.560,93.560,-7.065
2,ALB,1.0,91.768,91.768,-8.857
3,ALB,1.0,91.591,91.591,-9.034
4,ALB,1.0,91.422,91.422,-9.203
5,ALB,1.0,91.491,91.491,-9.134
6,ALB,1.0,91.438,91.438,-9.187
7,ALB,1.0,91.580,91.580,-9.045
8,ALB,1.0,91.644,91.644,-8.981
9,ALB,1.0,91.978,91.978,-8.647


```
Lap 1 was slow cause of the cold tyres, so every lap after looks "faster" relative to that slow start.

but this isn't capturing true degradation yet, we typically exclude the out-lap when measuring degradation and start the 'stint start' reference from lap 2 or 3 once the tyre has actually warmed up.
```

In [60]:
# Instead of comparing to lap 1 of the stint (which is artificially slow), compare to 
# lap 3 of the stint, by then the tyre has warmed up and we get a 
# true degradation baseline


def cal_degradation(group):
    # Use lap 3 as baseline if it exists, otherwise fall back to first available lap
    # This skips the slow out-lap(lap1) and warm-up lap (lap2)

    if len(group) >=3:
        baseline = group.iloc[2] #3rd lap of the stint
    else:
        baseline = group.iloc[0]

    return group - baseline



df["DegradationFromStintStart"] = df.groupby(
    ["RaceName", "Driver", "Stint"]
)["LapTime"].transform(cal_degradation)


df[df["Driver"] == "ALB"][["LapNumber", "LapTime", "DegradationFromStintStart"]].head(15)

,LapNumber,LapTime,DegradationFromStintStart
0,1.0,100.625,8.857
1,2.0,93.560,1.792
2,3.0,91.768,0.000
3,4.0,91.591,-0.177
4,5.0,91.422,-0.346
5,6.0,91.491,-0.277
6,7.0,91.438,-0.330
7,8.0,91.580,-0.188
8,9.0,91.644,-0.124
9,10.0,91.978,0.210


```
Laps 1-2   → warming up (slow → fast)
Laps 3-9   → peak performance window (fastest laps)
Laps 10+   → degradation creeping in (numbers trending positive)
```